version: '3.3'

services:
    app:
        container_name: nodeApp
        build: .
        image: node-app
        volumes:
            - .:/usr/src/app
        ports: 
            - '3000:3000'
        depends_on: 
            - mongo
        links: 
            - mongo
    mongo:
        container_name: mongoDB
        image: 'mongo'
        volumes:
            - ./data:/data/db
        env_file:
            - .env
        ports: 
            - '27017:27017'
volumes: 
    data: