version: '3.3'

services: 
    mongo:
        container_name: mongoDB
        image: 'mongo'
        volumes:
            - ./data:/data/db
        env_file:
            - .env
        ports: 
            - '27017:27017'
volumes: 
    data: